<?php

namespace App\Support\Onboarding;

class OnboardingRegistry
{
    public static function ownerSteps(): array
    {
        return [
            [
                'key' => 'welcome',
                'title' => 'Welcome to SRPM!',
                'content' => 'Let us walk you through the key features of your property management dashboard.',
                'target' => null,
                'placement' => 'center',
                'is_required' => true,
                'interaction' => 'acknowledge',
            ],
            [
                'key' => 'dashboard',
                'title' => 'Dashboard',
                'content' => 'Click Dashboard to view your property overview, income summary, and recent activity.',
                'target' => '[data-onboarding="owner-dashboard"]',
                'placement' => 'right',
                'is_required' => true,
                'interaction' => 'click',
            ],
            [
                'key' => 'dashboard_overview',
                'title' => 'Dashboard Overview',
                'content' => 'These cards show your total income, expenses, and net profit at a glance. Use the date filters above to adjust the period.',
                'target' => '[data-onboarding="owner-dashboard-overview"]',
                'placement' => 'bottom',
                'is_required' => true,
                'interaction' => 'acknowledge',
                'wait_for' => '[data-onboarding="owner-dashboard-overview"]',
            ],
            [
                'key' => 'leases',
                'title' => 'Leases',
                'content' => 'Click Leases to create and manage lease agreements, track terms, and handle renewals.',
                'target' => '[data-onboarding="owner-leases"]',
                'placement' => 'right',
                'is_required' => true,
                'interaction' => 'click',
            ],
            [
                'key' => 'units',
                'title' => 'Units & Rooms',
                'content' => 'Click Units to manage individual rooms within your properties — set rent, track occupancy, and assign tenants.',
                'target' => '[data-onboarding="owner-units"]',
                'placement' => 'right',
                'is_required' => true,
                'interaction' => 'click',
            ],
            [
                'key' => 'payments',
                'title' => 'Payments',
                'content' => 'Click Payments to monitor rent collections, track overdue amounts, and view payment history.',
                'target' => '[data-onboarding="owner-payments"]',
                'placement' => 'right',
                'is_required' => true,
                'interaction' => 'click',
            ],
            [
                'key' => 'requests',
                'title' => 'Complaints & Requests',
                'content' => 'Click Requests to manage maintenance requests and tenant complaints.',
                'target' => '[data-onboarding="owner-requests"]',
                'placement' => 'right',
                'is_required' => true,
                'interaction' => 'click',
            ],
            [
                'key' => 'faqs',
                'title' => 'FAQs',
                'content' => 'Click FAQs to create and organize frequently asked questions for your tenants.',
                'target' => '[data-onboarding="owner-faqs"]',
                'placement' => 'right',
                'is_required' => true,
                'interaction' => 'click',
            ],
            [
                'key' => 'properties',
                'title' => 'Properties',
                'content' => 'Click Properties to add and manage your rental properties.',
                'target' => '[data-onboarding="owner-properties"]',
                'placement' => 'right',
                'is_required' => true,
                'interaction' => 'click',
            ],
            [
                'key' => 'settings',
                'title' => 'Settings',
                'content' => 'Click Settings to configure your account, payment methods, and notification preferences.',
                'target' => '[data-onboarding="owner-settings"]',
                'placement' => 'right',
                'is_required' => true,
                'interaction' => 'click',
            ],
            [
                'key' => 'notifications',
                'title' => 'Notifications',
                'content' => 'Click the bell icon to view payment reminders, lease expirations, and complaint updates.',
                'target' => '[data-onboarding="notifications-bell"]',
                'placement' => 'bottom',
                'is_required' => true,
                'interaction' => 'acknowledge',
            ],
            [
                'key' => 'complete',
                'title' => 'You\'re All Set!',
                'content' => 'You\'ve completed the tour. You can restart it anytime from the sidebar. Happy managing!',
                'target' => null,
                'placement' => 'center',
                'is_required' => true,
                'interaction' => 'acknowledge',
            ],
        ];
    }

    public static function tenantSteps(): array
    {
        return [
            [
                'key' => 'welcome',
                'title' => 'Welcome to SRPM!',
                'content' => 'Let us show you around your tenant portal so you can make the most of it.',
                'target' => null,
                'placement' => 'center',
                'is_required' => true,
                'interaction' => 'acknowledge',
            ],
            [
                'key' => 'dashboard',
                'title' => 'Dashboard',
                'content' => 'Click Dashboard to see your lease details, upcoming payments, and important notifications.',
                'target' => '[data-onboarding="tenant-dashboard"]',
                'placement' => 'right',
                'is_required' => true,
                'interaction' => 'click',
            ],
            [
                'key' => 'dashboard_overview',
                'title' => 'Payment Overview',
                'content' => 'These cards show your next payment due, total paid, unpaid balance, and any penalties.',
                'target' => '[data-onboarding="tenant-dashboard-overview"]',
                'placement' => 'bottom',
                'is_required' => true,
                'interaction' => 'acknowledge',
                'wait_for' => '[data-onboarding="tenant-dashboard-overview"]',
            ],
            [
                'key' => 'leases',
                'title' => 'My Leases',
                'content' => 'Click Leases to view your current and past lease agreements, rent details, and lease status.',
                'target' => '[data-onboarding="tenant-leases"]',
                'placement' => 'right',
                'is_required' => true,
                'interaction' => 'click',
            ],
            [
                'key' => 'payments',
                'title' => 'Payments',
                'content' => 'Click Payments to track your payment history, upcoming due dates, and manage your rent.',
                'target' => '[data-onboarding="tenant-payments"]',
                'placement' => 'right',
                'is_required' => true,
                'interaction' => 'click',
            ],
            [
                'key' => 'requests',
                'title' => 'Complaints & Requests',
                'content' => 'Click Requests to submit maintenance requests or complaints and track their progress.',
                'target' => '[data-onboarding="tenant-requests"]',
                'placement' => 'right',
                'is_required' => true,
                'interaction' => 'click',
            ],
            [
                'key' => 'faqs',
                'title' => 'FAQs',
                'content' => 'Click FAQs to find answers to common questions about your lease, payments, and policies.',
                'target' => '[data-onboarding="tenant-faqs"]',
                'placement' => 'right',
                'is_required' => true,
                'interaction' => 'click',
            ],
            [
                'key' => 'settings',
                'title' => 'Settings',
                'content' => 'Click Settings to update your profile, change your password, and manage notifications.',
                'target' => '[data-onboarding="tenant-settings"]',
                'placement' => 'right',
                'is_required' => true,
                'interaction' => 'click',
            ],
            [
                'key' => 'notifications',
                'title' => 'Notifications',
                'content' => 'Click the bell icon to stay updated on payment reminders, maintenance updates, and notices.',
                'target' => '[data-onboarding="notifications-bell"]',
                'placement' => 'bottom',
                'is_required' => true,
                'interaction' => 'acknowledge',
            ],
            [
                'key' => 'complete',
                'title' => 'You\'re All Set!',
                'content' => 'You\'ve completed the tour. You can restart it anytime from the sidebar. Enjoy your stay!',
                'target' => null,
                'placement' => 'center',
                'is_required' => true,
                'interaction' => 'acknowledge',
            ],
        ];
    }
}
